### ISSUE TITLE
An idea about memory optimization

### ISSUE THREAD

**Issue by onting** [TargetExpert/TargetExpert#7]
I thought about a memory issue. A current implementation of the library create the object files about all peripheral's operation. Then, the object files, the all symbols and code should be loaded into memory(even if they are not used). So, I suggest following steps.
1. Remove all .c files to do not create object files.
2. Remove all declaration of functions in .h file 
3. Add mecro for implementing function in .h
Then machine program should be written as below.
1. Use implementing mecro as needed.
2. Use the function

Finally, we could reduce the size of program.
Please comment your opinions.

**Comment by GabrielKim** [comment]
Thank you for opinion.
But, I think you're something wrong, so let me explain a little bit.

1. After creating an object, copy the associated functions in the files of another linked object and create *.o (execution file and static library make this way. Shared library is different).

2. And there are Projects that need to be micro implemented in .c and .h files, and not.
The reason why I used this method this project is that it is more difficult because the macro is selectively generates each statement once and complies it when the code for the target device. but finally, the code comes the Peripherals of each MCU. It is more minimal.

Thank you for your opinion.
But first I would appreciate it if you think a little bit more about why this code came out.
